# Generated by Django 5.2.14 on 2026-05-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Indicates if the holiday has been processed for attendance'),
        ),
    ]
